### ISSUE TITLE
approximately how much data from the ood do we need for domain adaptation?

### ISSUE THREAD

**Issue by widdiot** [uds-lsv/da-lang-id#1]

**Comment by badrex** [comment]
Hi Vishay, 

This is a good question but we did not investigate this aspect in our work. In our paper, the number of speech samples from the (OOD) target domain was the same as the number of samples from the source domain. In most domain adaptation research papers, the assumption is that unlabelled samples from the target domain should be inexpensive to collect, thus one can use many samples from the target domain for adversarial domain adaptation. I am not sure to what extent this assumption holds in practice. But in case the number of samples from the target domain was limited, I would use a data augmentation strategy to create approximately the same number of samples in both source and target domains. 

Another strategy would be to sample from the source domain during batch creation. That is, for every batch an equal number of samples from source and target domains would be used. 

I hope this helped :)

Badr
